include: [README.md, Buildsystems.md, Design.md, CONTRIBUTING.md, LICENSE.txt, Makefile, index.html]
exclude: [include, scripts, build, caches, generators, buildsystems, buildtemplates, Gemfile*, .gitignore]

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
syntax_highlighter_opts: {
  line_numbers: false}